### ISSUE TITLE
Is the metadata storage flexible enough?

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro#30]
ATM repro stores metadata (which files, packages, scripts to use) on a per rmd basis:

```
---
title: "Test2"
author: "Aaron Peikert"
date: "1/13/2020"
output: html_document
repro:
  packages:
    - lubridate
    - readr
  data:
    - mtcars.csv
  scripts:
    - analyze.R
    - plots.R
---
```
And then uses the `automate_*` functions to parse this for interactive use, Makefile, Dockerfile etc.
The only problem with that approach so far is that the "R-Version" for Docker has to be guessed.

But is this general enough?

Is it compatible with the checksum/surrogate data mechanism, renv and everything else in worcs?
