### ISSUE TITLE
add tlmgr packages to yaml metadata

### ISSUE THREAD

**Issue by aaronpeikert** [aaronpeikert/repro#47]
papaja, bookdown etc require latex packages which ship not normally with the docker/verse container so it would be nice to add them to the metadata:

``` yaml
subtitle: "Automating reproducible research workflows"
author: "Aaron Peikert"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
repro:
  packages:
    - devtools
    - here
    - aaronpeikert/repro@1bb2e72d
    - bookdown
    - usethis
  tlmgr:
    - emptypage
    - sourcecodepro
    - libertinust1math
    - libertine
```
